server:
  port: 8781
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://192.168.99.100:9411/
#采样频率
  sleuth:
    sampler:
      probability: 1
#自定义负载策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#feign超时时间控制
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
#禁用hystrix超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeount:
#          enabled: false
#设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
#暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
env: master2002
branch: test
