server:
  port: 8772
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://192.168.99.100:9411/
#采样频率
  sleuth:
    sampler:
      probability: 1
env: master2019
branch: test
